### ISSUE TITLE
node2nix has a vulnerability

### ISSUE THREAD

**Issue by martindale** [FabricLabs/fabric#125]
After putting a bit more work into our dependency graph, `npm audit` now returns only this vulnerability:
```
# npm audit report

ssri  5.2.2 - 6.0.1
Severity: high
Regular Expression Denial of Service (ReDoS) - https://github.com/advisories/GHSA-vx3p-948g-6vhq
fix available via `npm audit fix --force`
Will install node2nix@1.6.0, which is a breaking change
node_modules/ssri
  npm-registry-client  >=8.5.1
  Depends on vulnerable versions of ssri
  node_modules/npm-registry-client
    node2nix  >=1.7.0
    Depends on vulnerable versions of npm-registry-client
    node_modules/node2nix

3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```

It's not clear if we should upgrade or _downgrade_ node2nix here, as we're using `1.11.0` in `package.json` but the audit suggests installing `1.6.0` — maybe @anandsuresh has some thoughts?

**Comment by anandsuresh** [comment]
We can remove this. We use `npmlock2nix` now which is much more reliable.

**Comment by martindale** [comment]
Looks like that brings us down to 0 vulnerabilities!  Also got the install down to 30 seconds 🥳

**Comment by anandsuresh** [comment]
Awesome work @martindale !!!!
